/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn make-types` to regenerate this file.
 */

export type LocalizedText =
  | string
  | {
      [k: string]: string
    }
/**
 * @minItems 1
 */
export type SchemaArray = [MiaSchema, ...MiaSchema[]]
export type StringArray = string[]

export interface Manifest {
  label?: LocalizedText
  description?: LocalizedText
  type?: "layout" | "connector" | "adapter"
  mocks?: {
    fetch?: Fetch
    [k: string]: unknown
  }
  properties?: {
    [k: string]: MiaSchema
  }
  [k: string]: unknown
}
export interface Fetch {
  context?: string[]
  routes?: {
    url: {
      origin?: string
      pathname: string
      search?: string
      [k: string]: unknown
    }
    method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE" | "OPTIONS" | "HEAD"
    handler?: (url: URL, context: Record<string, unknown>) => Promise<Response>
    [k: string]: unknown
  }[]
  [k: string]: unknown
}
export interface MiaSchema {
  $id?: string
  $schema?: string
  $ref?: string
  $comment?: string
  title?: string
  description?: string
  definitions?: {
    [k: string]: MiaSchema
  }
  type?:
    | ("array" | "boolean" | "integer" | "null" | "number" | "object" | "string")
    | [
        "array" | "boolean" | "integer" | "null" | "number" | "object" | "string",
        ...("array" | "boolean" | "integer" | "null" | "number" | "object" | "string")[]
      ]
  default?: true
  readOnly?: boolean
  writeOnly?: boolean
  examples?: true[]
  multipleOf?: number
  maximum?: number
  exclusiveMaximum?: number
  minimum?: number
  exclusiveMinimum?: number
  maxLength?: number
  minLength?: number
  pattern?: string
  additionalItems?: MiaSchema
  items?: MiaSchema | SchemaArray
  maxItems?: number
  minItems?: number
  uniqueItems?: boolean
  contains?: MiaSchema
  maxProperties?: number
  minProperties?: number
  properties?: {
    [k: string]: MiaSchema
  }
  additionalProperties?: MiaSchema
  patternProperties?: {
    [k: string]: MiaSchema
  }
  required?: StringArray
  dependencies?: {
    [k: string]: MiaSchema | StringArray
  }
  propertyNames?: MiaSchema
  const?: true
  /**
   * @minItems 1
   */
  enum?: [true, ...unknown[]]
  format?: string
  contentMediaType?: string
  contentEncoding?: string
  if?: MiaSchema
  then?: MiaSchema
  else?: MiaSchema
  allOf?: SchemaArray
  anyOf?: SchemaArray
  oneOf?: SchemaArray
  not?: MiaSchema
  __mia_configuration?: MiaConfiguration
  [k: string]: unknown
}
export interface MiaConfiguration {
  deprecated?:
    | boolean
    | {
        since?: string
        description?: LocalizedText
        [k: string]: unknown
      }
  label?: LocalizedText
  description?: LocalizedText
  oneOfGuard?: string
  oneOfDefault?: number
  priority?: "high" | "medium" | "low"
  attribute?: boolean | string
  "schema-hint"?: "localized-text" | "dynamic-icon" | "mia/endpoints/crud"
  "shared-key"?: "back-kit/data-schema" | string
}
