name: Tag Templates

env:
  context: './'
  node-version: 16.x

on:
  push:
    tags:
      - '@micro-lc/back-kit-templates'

jobs:
  cdn-publish:
    name: Publish templates on CDN
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Install mia's cdn-publish CLI
        run: npm i -g @mia-platform/cdn-publish:0.4.0

      - name: Publish to Mia CDN
        env:
          CDN_STORAGE_ACCESS_KEY: ${{ secrets.CDN_STORAGE_ACCESS_KEY }}
          CDN_STORAGE_ZONE_NAME: ${{ secrets.CDN_STORAGE_ZONE_NAME }}
        run: |
          cdn publish \
            -k "$CDN_STORAGE_ACCESS_KEY" \
            -s "$CDN_STORAGE_ZONE_NAME" \
            --project "./packages/templates/package.json" \
            --scope "backoffice/templates"
